/projects/bw83/anley1/Swin-Transformer-Object-Detection/mmdet/datasets/utils.py:68: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
/projects/bw83/anley1/conda_envs/swinEnv/lib/python3.7/site-packages/torch/nn/functional.py:3121: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
apex is not installed
apex is not installed
apex is not installed
apex is not installed
Use load_from_local loader
Traceback (most recent call last):
  File "run_inference.py", line 19, in <module>
    model.show_result(image_path, res, score_thr=0.3, show=False, win_name='result_out', bbox_color=(72,101,241), text_color=(72,101,241), out_file='result.jpg') 
  File "/projects/bw83/anley1/Swin-Transformer-Object-Detection/mmdet/models/detectors/cascade_rcnn.py", line 46, in show_result
    return super(CascadeRCNN, self).show_result(data, result, **kwargs)
  File "/projects/bw83/anley1/Swin-Transformer-Object-Detection/mmdet/models/detectors/base.py", line 352, in show_result
    out_file=out_file)
  File "/projects/bw83/anley1/Swin-Transformer-Object-Detection/mmdet/core/visualization/image.py", line 113, in imshow_det_bboxes
    fig = plt.figure(win_name, frameon=False)
  File "/projects/bw83/anley1/conda_envs/swinEnv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 693, in figure
    **kwargs)
  File "/projects/bw83/anley1/conda_envs/swinEnv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 315, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "/projects/bw83/anley1/conda_envs/swinEnv/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3494, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/projects/bw83/anley1/conda_envs/swinEnv/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 885, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/projects/bw83/anley1/conda_envs/swinEnv/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":1"
